---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
editor_options: 
  chunk_output_type: console
---

## Loading and preprocessing the data

```{r}

library(ggplot2)
library(dplyr)
library(knitr)
library(mice)

#set working dir
setwd("c:\\rprograms\\reproducibleresearch\\reproducibleresearch")

#download and unzip raw data from website
zipfile <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(zipfile, tf <- tempfile(fileext = ".zip"))
unzip(tf, exdir = td <- file.path(tempdir(), "myzip"))

# read csv data create datafram
rawdata <- read.csv(file.path(tempdir(), "/myzip/activity.csv"))
activitydata <- rawdata

#process data froma 
activitydata$date <- as.Date(as.character(activitydata$date))
activitydata <- activitydata[complete.cases(activitydata),]
activitydata$steps <- as.numeric(activitydata$steps)
activitydata$interval <-as.numeric(as.character(activitydata$interval))
```

## What is mean total number of steps taken per day?
```{r}



totalSteps <- aggregate(activitydata$steps, by=list(activitydata$date), sum, na.rm=TRUE)
                        
#use ggplot to create histogram from totalSteps data frame
ggplot(totalSteps, aes(x=totalSteps$Group.1, weights=totalSteps$x)) + geom_bar() 

myFun <- function(x) {
     c( 
       mean = as.numeric(mean(x), na.rm=TRUE), median = as.numeric(median(sort(x), na.rm=TRUE)))
}
tapply(activitydata$steps, activitydata$date, myFun)
```

## What is the average daily activity pattern?
```{r}



intervalSteps <- aggregate(activitydata$steps, by=list(activitydata$interval), mean, na.action=na.omit)
names(intervalSteps) <- c("Interval", "AverageSteps")
#plot interval data
plot.ts(intervalSteps$Interval, intervalSteps$AverageSteps, type="l")
#find max
maxinterval <- intervalSteps[order(intervalSteps$AverageSteps),]


## Imputing missing values
pMiss <- function(x){sum(is.na(x))/length(x)*100}
apply(rawdata,2,pMiss)

md.pattern(rawdata)

impdata <- mice(rawdata,m=5,maxit=5,meth='mean')
summary(impdata)

completedata <- complete(impdata,1)
tapply(completedata$steps, completedata$date, myFun)

ggplot(completedata, aes(x=completedata$date, weights=completedata$steps)) + geom_bar() 
```


## Are there differences in activity patterns between weekdays and weekends?
#add column to completedata for weekend weekday indicator
```{r}

completedata$weekend <- grepl("S.+", weekdays(as.Date(completedata$date)))

#panel plot of weekend v weekday data
#plot graphs in 2x2 panel

par(mfrow = c(2,1), mar=c(0, 4, 1, 1) + 0.1)#it goes c(bottom, left, top, right) 


weekenddata <- subset(completedata, weekend == TRUE)
weekendintervalsteps <- aggregate(weekenddata$steps, by=list(weekenddata$interval)
                                  , mean, na.action=na.omit)
weekdaydata <- subset(completedata, weekend == FALSE)
weekdayintervalsteps <- aggregate(weekdaydata$steps, by=list(weekdaydata$interval)
                                  , mean, na.action=na.omit)

par(mar=c(3,4,4,1)+0.1)

#create plot a
plot.ts(weekendintervalsteps$Group.1, weekendintervalsteps$x, type="l",  main="Weekend", ylab="", xlab="", xaxt='n')

#create plot b
plot.ts(weekdayintervalsteps$Group.1, weekdayintervalsteps$x, type="l",  main="Weekday", ylab="", xlab="interval", xlim=c(0,3000))
```